name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: yarn install, yarn lint, yarn generate
      run: |
        yarn install
        yarn generate
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with: 
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: dist
        clean: true
        clean-exclude: |
          CNAME
          .nojekyll